version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000:5000"
  proxy:
    build:
      context: ./ngnix
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    links:
      - app
  redis:
    image: "redis:alpine"